spring:
  datasources:
    mysql:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
      url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC
      hikari:
        auto-commit: false
        maximum-pool-size: 10
      jpa:
        properties:
          hibernate.dialect: org.hibernate.dialect.MySQLDialect
          show-sql: true

server:
  port: 3110
